-- GENERATED from the live catalog by tools/verify_migration_chain.py --refresh-legacy.
-- Column names and types only. No rows are read and none are written; a column name is
-- not an observation. These tables predate the migration chain and no migration file
-- creates them, so a rebuild from empty is impossible without them (ADR-0088).

CREATE TABLE IF NOT EXISTS public.ask_threads (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "user_id" uuid NOT NULL,
    "title" text,
    "last_frame" jsonb,
    "turns" jsonb NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.briefs (
    "user_id" uuid NOT NULL,
    "day" date NOT NULL,
    "text" text NOT NULL,
    "why" text,
    "sent_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.category_map (
    "raw_key" text NOT NULL,
    "category" text NOT NULL,
    "pillar" text NOT NULL,
    "sort" integer NOT NULL
);
CREATE TABLE IF NOT EXISTS public.checkin_probe_queue (
    "id" bigint NOT NULL,
    "user_id" uuid NOT NULL,
    "day" date NOT NULL,
    "probe_key" text NOT NULL,
    "reason" text,
    "rank" integer,
    "created_at" timestamp with time zone DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.checkin_probes (
    "id" bigint NOT NULL,
    "key" text NOT NULL,
    "question" text NOT NULL,
    "answer_type" text NOT NULL,
    "choices" jsonb,
    "trigger" text NOT NULL,
    "informs" text,
    "priority" integer NOT NULL,
    "active" boolean NOT NULL
);
CREATE TABLE IF NOT EXISTS public.checkins (
    "id" bigint NOT NULL,
    "user_id" uuid NOT NULL,
    "ts" timestamp with time zone NOT NULL,
    "checkin_date" date NOT NULL,
    "type" text NOT NULL,
    "restored" integer,
    "energy" integer,
    "mood" integer,
    "mental_clarity" integer,
    "drive" integer,
    "stress" integer,
    "mental_sharpness" integer,
    "note" text,
    "meta" jsonb,
    "ingested_at" timestamp with time zone DEFAULT now() NOT NULL,
    "sleep_feel" integer,
    "day_rating" integer
);
CREATE TABLE IF NOT EXISTS public.coach_recommendations (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "user_id" uuid NOT NULL,
    "run_day" date DEFAULT now() NOT NULL,
    "coach" text NOT NULL,
    "domain" text,
    "verdict" text,
    "headline" text,
    "body" text,
    "readiness_note" text,
    "actions" jsonb NOT NULL,
    "evidence" jsonb,
    "confidence" text,
    "consulted" text[] NOT NULL,
    "status" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.confrontations (
    "id" bigint NOT NULL,
    "user_id" uuid NOT NULL,
    "ts" timestamp with time zone DEFAULT now(),
    "type" text NOT NULL,
    "statement" text NOT NULL,
    "evidence" jsonb,
    "materiality" numeric,
    "failure_mode" text,
    "status" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.content_taxonomy (
    "key" text NOT NULL,
    "kind" text NOT NULL,
    "category" text NOT NULL
);
CREATE TABLE IF NOT EXISTS public.context_facts (
    "id" bigint NOT NULL,
    "user_id" uuid NOT NULL,
    "kind" text NOT NULL,
    "label" text NOT NULL,
    "value" jsonb NOT NULL,
    "start_date" date,
    "end_date" date,
    "status" text NOT NULL,
    "provenance" jsonb,
    "created_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.day_narratives (
    "user_id" uuid NOT NULL,
    "day" date NOT NULL,
    "text" text,
    "model" text,
    "input_hash" text,
    "generated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.entities (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" uuid NOT NULL,
    "type" text NOT NULL,
    "name" text NOT NULL,
    "norm_name" text NOT NULL,
    "lat" double precision,
    "lon" double precision,
    "category" text,
    "attributes" jsonb NOT NULL,
    "confirmed" boolean NOT NULL,
    "occurrence_count" integer NOT NULL,
    "first_seen" date,
    "last_seen" date,
    "total_amount" numeric,
    "source" text,
    "provenance" jsonb NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "life_category" text,
    "pillar" text
);
CREATE TABLE IF NOT EXISTS public.entity_occurrences (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" uuid NOT NULL,
    "entity_id" bigint NOT NULL,
    "ts" timestamp with time zone NOT NULL,
    "day" date NOT NULL,
    "dow" integer,
    "hour" integer,
    "dwell_min" double precision,
    "amount" numeric,
    "transaction_id" bigint,
    "inferred_event_id" bigint,
    "checkin_id" bigint,
    "location_ref" jsonb,
    "confidence" numeric,
    "provenance" jsonb NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.events (
    "id" bigint NOT NULL,
    "user_id" uuid NOT NULL,
    "ts" timestamp with time zone NOT NULL,
    "kind" text NOT NULL,
    "payload" jsonb,
    "ingested_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.experiment_assignments (
    "id" bigint NOT NULL,
    "user_id" uuid NOT NULL,
    "experiment_key" text NOT NULL,
    "target_lever" text NOT NULL,
    "day" date NOT NULL,
    "condition" text NOT NULL,
    "assigned_at" timestamp with time zone DEFAULT now(),
    "complied" boolean,
    "compliance_source" text
);
CREATE TABLE IF NOT EXISTS public.experiments (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" uuid NOT NULL,
    "driver" text NOT NULL,
    "outcome" text NOT NULL,
    "hypothesis" text,
    "design" jsonb NOT NULL,
    "status" text NOT NULL,
    "method" text,
    "result" jsonb,
    "verdict" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.forecast_log (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "user_id" uuid NOT NULL,
    "made_on" date NOT NULL,
    "target_day" date NOT NULL,
    "metric" text NOT NULL,
    "predicted" numeric,
    "lo" numeric,
    "hi" numeric,
    "confidence_word" text,
    "realized" numeric,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.goals (
    "id" bigint NOT NULL,
    "user_id" uuid NOT NULL,
    "category" text,
    "key" text NOT NULL,
    "statement" text,
    "target" numeric,
    "unit" text,
    "cadence" text,
    "direction" text NOT NULL,
    "start_date" date,
    "active" boolean NOT NULL,
    "meta" jsonb,
    "created_at" timestamp with time zone DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.graph_structures (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" uuid,
    "kind" text NOT NULL,
    "hops" integer,
    "nodes" jsonb NOT NULL,
    "edges" jsonb NOT NULL,
    "statement" text,
    "path_strength" numeric,
    "min_tier" text,
    "all_oos" boolean,
    "total_lag" integer,
    "verdict" text,
    "intervention_node" text,
    "categories" text[],
    "meta" jsonb,
    "code_version" text,
    "created_at" timestamp with time zone DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.hypotheses (
    "id" bigint NOT NULL,
    "user_id" uuid NOT NULL,
    "kind" text NOT NULL,
    "statement" text NOT NULL,
    "driver" text,
    "outcome" text,
    "lag" integer,
    "effect" double precision,
    "n" integer,
    "evidence_for" jsonb,
    "evidence_against" jsonb,
    "score" double precision,
    "verdict" text,
    "provenance" jsonb,
    "code_version" text,
    "created_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.inferred_events (
    "id" bigint NOT NULL,
    "user_id" uuid NOT NULL,
    "ts" timestamp with time zone NOT NULL,
    "day" date NOT NULL,
    "kind" text NOT NULL,
    "source" text NOT NULL,
    "label" text NOT NULL,
    "amount" numeric,
    "currency" text,
    "merchant" text,
    "likely_payment" text,
    "calories" numeric,
    "protein_g" numeric,
    "fat_g" numeric,
    "carbs_g" numeric,
    "confidence" numeric,
    "status" text NOT NULL,
    "provenance" jsonb,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.ingest_status (
    "user_id" uuid NOT NULL,
    "source" text NOT NULL,
    "last_ingest_at" timestamp with time zone DEFAULT now() NOT NULL,
    "last_rows" integer NOT NULL,
    "last_workouts" integer NOT NULL,
    "last_quarantined" integer NOT NULL
);
CREATE TABLE IF NOT EXISTS public.insights (
    "id" bigint NOT NULL,
    "user_id" uuid NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "title" text NOT NULL,
    "body" text,
    "confidence" numeric,
    "evidence" jsonb,
    "status" text NOT NULL
);
CREATE TABLE IF NOT EXISTS public.insights_catalog (
    "id" bigint NOT NULL,
    "user_id" uuid NOT NULL,
    "family" text NOT NULL,
    "domain" text,
    "subject" text,
    "statement" text NOT NULL,
    "effect" numeric,
    "lag" integer,
    "n" integer,
    "confidence" text,
    "tier" text,
    "materiality" numeric,
    "evidence" jsonb NOT NULL,
    "status" text NOT NULL,
    "first_seen" date DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "category" text,
    "pillar" text
);
CREATE TABLE IF NOT EXISTS public.intraday (
    "id" bigint NOT NULL,
    "user_id" uuid NOT NULL,
    "series" text NOT NULL,
    "ts" timestamp with time zone NOT NULL,
    "end_ts" timestamp with time zone,
    "value" double precision,
    "text_value" text,
    "unit" text,
    "meta" jsonb,
    "day" date,
    "created_at" timestamp with time zone DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.locations (
    "id" bigint NOT NULL,
    "user_id" uuid NOT NULL,
    "ts" timestamp with time zone NOT NULL,
    "lat" double precision NOT NULL,
    "lon" double precision NOT NULL,
    "accuracy" double precision,
    "altitude" double precision,
    "velocity" double precision,
    "course" double precision,
    "battery" integer,
    "trigger" text,
    "meta" jsonb,
    "ingested_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.merchant_taxonomy (
    "key" text NOT NULL,
    "category" text NOT NULL
);
CREATE TABLE IF NOT EXISTS public.metric_catalog (
    "feature" text NOT NULL,
    "domain" text NOT NULL,
    "bare" text NOT NULL,
    "pretty" text NOT NULL,
    "tokens" text[] NOT NULL,
    "n_days" integer,
    "last_day" date,
    "validity" text
);
CREATE TABLE IF NOT EXISTS public.place_book (
    "id" bigint NOT NULL,
    "user_id" uuid NOT NULL,
    "name" text NOT NULL,
    "lat" double precision NOT NULL,
    "lon" double precision NOT NULL,
    "place_type" text,
    "cuisine" text,
    "visit_count" integer NOT NULL,
    "confirmed" boolean NOT NULL,
    "first_seen" date,
    "last_seen" date,
    "source" text,
    "provenance" jsonb,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.reconcile_queue (
    "id" bigint NOT NULL,
    "user_id" uuid NOT NULL,
    "inferred_id" bigint NOT NULL,
    "task" text NOT NULL,
    "status" text NOT NULL,
    "result" jsonb,
    "created_at" timestamp with time zone DEFAULT now(),
    "done_at" timestamp with time zone
);
CREATE TABLE IF NOT EXISTS public.signals (
    "id" bigint NOT NULL,
    "user_id" uuid NOT NULL,
    "ts" timestamp with time zone NOT NULL,
    "source" text NOT NULL,
    "metric" text NOT NULL,
    "value" double precision,
    "value_text" text,
    "unit" text,
    "meta" jsonb,
    "ingested_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.transactions (
    "id" bigint NOT NULL,
    "user_id" uuid NOT NULL,
    "ts" timestamp with time zone NOT NULL,
    "amount" numeric NOT NULL,
    "currency" text NOT NULL,
    "merchant" text,
    "category" text,
    "source" text NOT NULL,
    "meta" jsonb,
    "ingested_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.validated_insights (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" uuid NOT NULL,
    "driver" text NOT NULL,
    "outcome" text NOT NULL,
    "best_lag" integer,
    "r" double precision,
    "direction" text,
    "n" integer,
    "fdr_q" double precision,
    "method" text NOT NULL,
    "split_half_stable" boolean,
    "oos_held" boolean,
    "redundant_suspect" boolean,
    "meta" jsonb NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE IF NOT EXISTS public.workouts (
    "id" bigint NOT NULL,
    "user_id" uuid NOT NULL,
    "start_ts" timestamp with time zone NOT NULL,
    "end_ts" timestamp with time zone,
    "type" text NOT NULL,
    "load" numeric,
    "source" text NOT NULL,
    "meta" jsonb,
    "ingested_at" timestamp with time zone DEFAULT now() NOT NULL
);
