"""Private transaction-scoped persistence of Chase source observations (ADR0171).

Caller owns commit/rollback. Only original bytes enter this boundary; normalized
rows are always regenerated by the versioned parser, never accepted from a client.
"""
from collections import defaultdict, deque
import json
import uuid

from tools.importers.v0_card import prepare


def import_bytes(cur, data, account_id, *, schema='core'):
    """Save an immutable receipt; exact bytes replay the same receipt for this account.

    Full-file row multiset equivalence preserves different source bytes as aliases.
    Potential partial overlaps remain explicit review candidates, not deduped facts.
    This function does not commit. A failure must roll back the caller transaction.
    """
    if schema not in ('core', 'core_pytest'):
        raise ValueError('unsupported card storage schema')
    if cur.connection.autocommit:
        raise ValueError('card import requires a caller-owned transaction')
    request = prepare(data, account_id)
    account = request['account_id']
    cur.execute('SHOW transaction_isolation')
    if cur.fetchone()[0] != 'read committed':
        raise ValueError('card import requires READ COMMITTED isolation')
    cur.execute('SELECT pg_advisory_xact_lock(9171001)')
    cur.execute(f'SELECT receipt FROM {schema}.v0_card_files WHERE account_id=%s AND source_sha256=%s',
                (account, request['source_sha256']))
    existing = cur.fetchone()
    if existing:
        return existing[0]
    cur.execute(f'''SELECT file_id FROM {schema}.v0_card_files
        WHERE account_id=%s AND content_digest=%s AND mapping_version=%s AND equivalent_to IS NULL
        ORDER BY recorded_at,file_id LIMIT 1''',
        (account, request['content_digest'], request['mapping_version']))
    equivalent = cur.fetchone()
    equivalent_id = str(equivalent[0]) if equivalent else None
    aliases = defaultdict(deque)
    if equivalent_id:
        cur.execute(f'''SELECT row_digest,row_id FROM {schema}.v0_card_rows
            WHERE file_id=%s ORDER BY source_row''', (equivalent_id,))
        for row_digest, row_id in cur.fetchall():
            aliases[row_digest].append(str(row_id))

    file_id = str(uuid.uuid4())
    # Import time is capture time here; transaction dates are separately preserved
    # at date precision. Never turn file mtime into transaction occurrence time.
    cur.execute('SELECT clock_timestamp()')
    imported_at = cur.fetchone()[0]
    payload = dict(kind='v0_card_source', account_id=account,
                   mapping_version=request['mapping_version'],
                   source_sha256=request['source_sha256'],
                   source_base64=request['source_base64'], capture_time_basis='import_received')
    cur.execute(f'''INSERT INTO {schema}.raw_captures
        (capture_id,captured_at,source,trust_level,payload)
        VALUES (%s,%s,'file_import','untrusted',%s::jsonb)''',
        (file_id, imported_at, json.dumps(payload)))

    # Plan all rows before inserting their file receipt; include earlier rows from
    # this same file in candidate lookup so identical source multiplicity survives.
    cur.execute(f'''SELECT row_id,row_digest,occurred_on,amount,currency,source_type,description
        FROM {schema}.v0_card_rows WHERE account_id=%s AND equivalent_row_id IS NULL
        ORDER BY recorded_at,file_id,source_row''', (account,))
    prior = list(cur.fetchall())
    planned = []
    from datetime import date
    from decimal import Decimal
    for row in request['rows']:
        rid = str(uuid.uuid4())
        alias = aliases[row['row_digest']].popleft() if equivalent_id else None
        candidates = []
        day = date.fromisoformat(row['occurred_on'])
        amount = Decimal(row['amount'])
        if not alias:
            for pid, pdigest, pday, pamount, currency, kind, description in prior:
                # Candidate evidence only. Same stated day/amount/type is ambiguous
                # even if a later export changes the merchant spelling or memo.
                # Near-date matches require the same merchant text as well.
                same_value = currency == row['currency'] and kind == row['source_type'] and pamount == amount
                near = abs((day-pday).days) <= 3 and description.strip().casefold() == row['description'].strip().casefold()
                if pdigest == row['row_digest'] or (same_value and (day == pday or near)):
                    candidates.append(str(pid))
        status = 'equivalent_file' if alias else ('needs_review' if candidates else 'distinct')
        planned.append((rid, row, status, alias, candidates))
        if not alias:
            prior.append((rid,row['row_digest'],day,amount,row['currency'],row['source_type'],row['description']))
    receipt = dict(status='saved',file_id=file_id,account_id=account,
                   source_sha256=request['source_sha256'],mapping_version=request['mapping_version'],
                   source_rows=len(planned),equivalent_to=equivalent_id,
                   distinct_rows=sum(p[2]=='distinct' for p in planned),
                   review_rows=sum(p[2]=='needs_review' for p in planned),
                   equivalent_rows=sum(p[2]=='equivalent_file' for p in planned),
                   imported_at=imported_at.isoformat(),identity_scope='source_observations')
    cur.execute(f'''INSERT INTO {schema}.v0_card_files
        (file_id,account_id,source_sha256,content_digest,mapping_version,equivalent_to,receipt)
        VALUES (%s,%s,%s,%s,%s,%s,%s::jsonb)''',
        (file_id,account,request['source_sha256'],request['content_digest'],
         request['mapping_version'],equivalent_id,json.dumps(receipt)))
    for rid,row,status,alias,candidates in planned:
        cur.execute(f'''INSERT INTO {schema}.v0_card_rows
            (row_id,file_id,account_id,source_row,source_record,row_digest,occurred_on,
             posted_on,amount,currency,source_type,source_category,description,memo,
             initial_status,equivalent_row_id,candidate_ids)
            VALUES (%s,%s,%s,%s,%s::jsonb,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s::uuid[])''',
            (rid,file_id,account,row['source_row'],json.dumps(row['source_record']),row['row_digest'],
             row['occurred_on'],row['posted_on'],row['amount'],row['currency'],row['source_type'],
             row['source_category'],row['description'],row['memo'],status,alias,candidates))
    return receipt
